on:
  push:
    tags:
      - v5.0.0-rc.*

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install dependencies
        run: yarn install
      - name: Build project
        run: yarn build
      - name: Set the publish version
        run: npm version ${GITHUB_REF#refs/tags/v}
      - name: Publish
        run: npm publish --tag rc
