on:
  push:
    tags:
      - v5.0.0-rc.*

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.13.x"
      - name: Install dependencies
        run: yarn install
      - name: Build project
        run: yarn build
        working-directory: ./plugin
      - name: Set the publish version
        run: npm version ${GITHUB_REF#refs/tags/v}
        working-directory: ./plugin
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: rc
